# THIS FILE IS AUTOMATICALLY GENERATED
# Project: C:\Users\akita\Documents\TPT02\src\Hibernate_PSoC4_Example01.cydsn\Hibernate_PSoC4_Example01.cyprj
# Date: Fri, 21 Apr 2017 03:50:17 GMT
#set_units -time ns
create_clock -name {CyRouted1} -period 41.666666666666664 -waveform {0 20.8333333333333} [list [get_pins {ClockBlock/dsi_in_0}]]
create_clock -name {CyILO} -period 31250 -waveform {0 15625} [list [get_pins {ClockBlock/ilo}]]
create_clock -name {CyLFCLK} -period 31250 -waveform {0 15625} [list [get_pins {ClockBlock/lfclk}]]
create_clock -name {CyIMO} -period 41.666666666666664 -waveform {0 20.8333333333333} [list [get_pins {ClockBlock/imo}]]
create_clock -name {CyHFCLK} -period 41.666666666666664 -waveform {0 20.8333333333333} [list [get_pins {ClockBlock/hfclk}]]
create_clock -name {CySYSCLK} -period 41.666666666666664 -waveform {0 20.8333333333333} [list [get_pins {ClockBlock/sysclk}]]


# Component constraints for C:\Users\akita\Documents\TPT02\src\Hibernate_PSoC4_Example01.cydsn\TopDesign\TopDesign.cysch
# Project: C:\Users\akita\Documents\TPT02\src\Hibernate_PSoC4_Example01.cydsn\Hibernate_PSoC4_Example01.cyprj
# Date: Fri, 21 Apr 2017 03:50:15 GMT
